"use client";
import { FormEvent, useState } from "react";
import { createUserWithEmailAndPassword, GoogleAuthProvider, sendEmailVerification, signInWithEmailAndPassword, signInWithPopup, signOut, updateProfile, User } from "firebase/auth";
import { firebaseAuth } from "../firebase-client";

export default function Login(){const [register,setRegister]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  async function finish(user:User){if(!user.emailVerified){await sendEmailVerification(user);await signOut(firebaseAuth);setNotice("Te enviamos un correo de verificación. Ábrelo antes de iniciar sesión.");setBusy(false);return}const response=await fetch("/api/auth/firebase",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idToken:await user.getIdToken()})});const body=await response.json();if(!response.ok)throw new Error(body.error);window.location.href="/"}
  async function google(){setBusy(true);setError("");setNotice("");try{await finish((await signInWithPopup(firebaseAuth,new GoogleAuthProvider())).user)}catch(error){setError(authMessage(error));setBusy(false)}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setNotice("");const form=new FormData(event.currentTarget);const email=String(form.get("email")||"");const password=String(form.get("password")||"");try{if(register){const credential=await createUserWithEmailAndPassword(firebaseAuth,email,password);await updateProfile(credential.user,{displayName:String(form.get("displayName")||"")});await finish(credential.user)}else await finish((await signInWithEmailAndPassword(firebaseAuth,email,password)).user)}catch(error){setError(authMessage(error));setBusy(false)}}
  return <main className="auth-page"><section className="auth-card"><div className="brand auth-brand"><span className="brand-mark">C</span><span>Cyc—AI</span></div><p className="eyebrow">Tu entrenamiento, en un solo lugar</p><h1>{register?"Crea tu cuenta":"Bienvenido"}</h1><p className="sub">Conecta tus aplicaciones deportivas y sincroniza automáticamente tus actividades.</p><button className="social-button" onClick={()=>void google()} disabled={busy}><span className="google-g">G</span>Continuar con Google</button><div className="auth-divider"><span>o</span></div><form onSubmit={submit}>{register&&<label>Nombre<input name="displayName" minLength={2} required autoComplete="name"/></label>}<label>Correo<input name="email" type="email" required autoComplete="email"/></label><label>Contraseña<input name="password" type="password" minLength={8} required autoComplete={register?"new-password":"current-password"}/></label>{error&&<p className="form-error">{error}</p>}{notice&&<p className="form-notice">{notice}</p>}<button className="primary" disabled={busy}>{busy?"Espera…":register?"Crear cuenta":"Entrar"}</button></form><button className="auth-switch" onClick={()=>{setRegister(value=>!value);setError("");setNotice("")}}>{register?"Ya tengo una cuenta":"Crear una cuenta nueva"}</button><p className="apple-note">Inicio con Apple estará disponible más adelante.</p></section></main>}
function authMessage(error:unknown){const code=typeof error==="object"&&error&&"code" in error?String(error.code):"";if(code.includes("email-already-in-use"))return "Ese correo ya está registrado.";if(code.includes("invalid-credential"))return "Correo o contraseña incorrectos.";if(code.includes("popup-closed"))return "Cerraste la ventana de Google antes de terminar.";if(code.includes("unauthorized-domain"))return "Este dominio todavía no está autorizado en Firebase.";return error instanceof Error?error.message:"No fue posible continuar."}
